# Generated by Django 5.0.6 on 2025-03-10 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='current_price',
        ),
    ]
