# Generated by Django 5.0.6 on 2025-03-11 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_remove_bid_price_alter_auctionlisting_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='auction_listing',
            new_name='listing',
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='created_at',
            new_name='time_stamp',
        ),
        migrations.AddField(
            model_name='bid',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='starting_bid',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
