# Generated by Django 5.0.6 on 2025-03-11 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0005_rename_auction_listing_bid_listing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
