# Generated by Django 5.0.6 on 2025-03-11 21:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0006_alter_auctionlisting_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
