# Generated by Django 5.0.6 on 2025-03-16 16:58

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0008_alter_auctionlisting_image'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='auctionlisting',
            managers=[
                ('custom_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
