# Generated by Django 5.0.6 on 2025-03-19 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0009_alter_auctionlisting_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='auctionlisting',
            managers=[
            ],
        ),
    ]
