# Generated by Django 5.0.6 on 2025-03-19 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0010_alter_auctionlisting_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='time_stamp',
            new_name='timestamp',
        ),
        migrations.AlterField(
            model_name='bid',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bid',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auction.auctionlisting'),
        ),
    ]
