# Generated by Django 5.0.6 on 2025-03-19 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0011_rename_time_stamp_bid_timestamp_alter_bid_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
