# Generated by Django 5.0.6 on 2025-03-19 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0015_alter_auctionlisting_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='image',
            field=models.ImageField(default='cars.png', null=True, upload_to=''),
        ),
    ]
