# Generated by Django 5.0.6 on 2025-03-26 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0016_alter_auctionlisting_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='listing',
            new_name='item',
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='image',
            field=models.ImageField(default='images/default_background.jpg', null=True, upload_to='images/'),
        ),
    ]
