# Generated by Django 5.0.6 on 2025-04-04 19:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0018_remove_auctionlisting_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='start_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
