# Generated by Django 5.0.6 on 2025-04-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0021_rename_item_bid_auction_bid_bidder_alter_bid_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
