# Generated by Django 5.0.7 on 2025-04-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0022_auctionlisting_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='is_ongoing',
            field=models.BooleanField(default=True),
        ),
    ]
