# Generated by Django 5.0.7 on 2025-04-12 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0023_auctionlisting_is_ongoing'),
        ('user', '0003_alter_profile_email_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='sold_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='user.profile'),
        ),
    ]
